import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const userFollows = sqliteTable("user_follows", {followerId: text('follower_id').notNull(),
	followingId: text('following_id').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const userBlocks = sqliteTable("user_blocks", {userId: text('user_id').notNull(),
	blockedId: text('blocked_id').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const commentMentions = sqliteTable("comment_mentions", {commentId: text('comment_id').notNull(),
	mentionedUserId: text('mentioned_user_id').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const xpAwards = sqliteTable("xp_awards", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	userId: text('user_id').notNull(),
	chapterId: text('chapter_id').notNull(),
	workId: text('work_id').notNull(),
	amount: integer('amount').notNull(),
	source: text('source').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const mihonTokens = sqliteTable("mihon_tokens", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	userId: text('user_id').notNull(),
	tokenHash: text('token_hash').notNull(),
	tokenType: text('token_type').notNull(),
	scopes: text('scopes').notNull(),
	expiresAt: text('expires_at').notNull(),
	revoked: integer('revoked', { mode: 'boolean' }).notNull(),
	deviceName: text('device_name'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const reports = sqliteTable("reports", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	reporterId: text('reporter_id').notNull(),
	targetType: text('target_type').notNull(),
	workId: text('work_id'),
	chapterId: text('chapter_id'),
	targetUserId: text('target_user_id'),
	commentId: text('comment_id'),
	reason: text('reason').notNull(),
	details: text('details'),
	status: text('status').notNull(),
	assignedTo: text('assigned_to'),
	resolutionNotes: text('resolution_notes'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const memberAchievements = sqliteTable("member_achievements", {userId: text('user_id').notNull(),
	achievementId: text('achievement_id').notNull(),
	unlockedAt: text('unlocked_at').notNull(),});

export const achievements = sqliteTable("achievements", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	title: text('title').notNull(),
	description: text('description').notNull(),
	category: text('category').notNull(),
	icon: text('icon').notNull(),
	badgeColor: text('badge_color').notNull(),
	xpReward: integer('xp_reward').notNull(),
	conditionType: text('condition_type').notNull(),
	conditionValue: integer('condition_value').notNull(),
	isSecret: integer('is_secret').notNull(),
	orderIndex: integer('order_index').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	rarity: text('rarity').notNull(),
	rewardItemId: text('reward_item_id'),});

export const chapterReactions = sqliteTable("chapter_reactions", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	chapterId: text('chapter_id').notNull(),
	visitorId: text('visitor_id').notNull(),
	emoji: text('emoji').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const shopItems = sqliteTable("shop_items", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	name: text('name').notNull(),
	description: text('description').notNull(),
	kind: text('kind').notNull(),
	priceXp: integer('price_xp').notNull(),
	isAnimated: integer('is_animated').notNull(),
	assetUrl: text('asset_url').notNull(),
	styleData: text('style_data').notNull(),
	minLevel: integer('min_level').notNull(),
	isActive: integer('is_active', { mode: 'boolean' }).notNull(),
	orderIndex: integer('order_index').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	rarity: text('rarity').notNull(),
	status: text('status').notNull(),
	thumbnailUrl: text('thumbnail_url'),});

export const memberInventory = sqliteTable("member_inventory", {userId: text('user_id').notNull(),
	itemId: text('item_id').notNull(),
	acquiredAt: text('acquired_at').notNull(),
	origin: text('origin').notNull(),});

export const importerStaffRequests = sqliteTable("importer_staff_requests", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	workId: text('work_id').notNull(),
	requestedBy: text('requested_by').notNull(),
	priorityBoost: integer('priority_boost').notNull(),
	reason: text('reason'),
	status: text('status').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),
	cancelledBy: text('cancelled_by'),
	cancelledAt: text('cancelled_at'),
	cancelReason: text('cancel_reason'),
	lastError: text('last_error'),
	lastAttemptAt: text('last_attempt_at'),
	nextAttemptAt: text('next_attempt_at'),
	attemptCount: integer('attempt_count').notNull(),});

export const scanInvites = sqliteTable("scan_invites", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	code: text('code').notNull(),
	role: text('role').notNull(),
	createdBy: text('created_by').notNull(),
	expiresAt: text('expires_at').notNull(),
	usedAt: text('used_at'),
	usedBy: text('used_by'),
	revoked: integer('revoked', { mode: 'boolean' }).notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	invitedUserId: text('invited_user_id'),
	positionId: text('position_id'),
	status: text('status').notNull(),
	revokedAt: text('revoked_at'),
	declinedAt: text('declined_at'),});

export const importerChapterManifest = sqliteTable("importer_chapter_manifest", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	workId: text('work_id').notNull(),
	chapterNumber: real('chapter_number').notNull(),
	chapterSortKey: integer('chapter_sort_key').notNull(),
	chapterTitle: text('chapter_title'),
	status: text('status').notNull(),
	selectedSource: text('selected_source'),
	availableSources: text('available_sources').notNull(),
	pageCount: integer('page_count'),
	lastCheckedAt: text('last_checked_at').notNull(),});

export const importerWorkHealth = sqliteTable("importer_work_health", {workId: text('work_id').notNull(),
	healthStatus: text('health_status').notNull(),
	totalKnownChapters: integer('total_known_chapters').notNull(),
	totalImportedChapters: integer('total_imported_chapters').notNull(),
	missingStart: integer('missing_start').notNull(),
	firstChapterNumber: real('first_chapter_number'),
	latestChapterNumber: real('latest_chapter_number'),
	gaps: text('gaps').notNull(),
	unresolvedGaps: text('unresolved_gaps').notNull(),
	providersSummary: text('providers_summary').notNull(),
	lastReconciledAt: text('last_reconciled_at').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const scanProjectRequests = sqliteTable("scan_project_requests", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	workId: text('work_id').notNull(),
	userId: text('user_id').notNull(),
	message: text('message'),
	status: text('status').notNull(),
	reviewedBy: text('reviewed_by'),
	reviewedAt: text('reviewed_at'),
	rejectionReason: text('rejection_reason'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanPartnerRequests = sqliteTable("scan_partner_requests", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	userId: text('user_id').notNull(),
	scanName: text('scan_name').notNull(),
	scanSlug: text('scan_slug').notNull(),
	description: text('description'),
	discord: text('discord'),
	fluxer: text('fluxer'),
	website: text('website'),
	sampleLinks: text('sample_links'),
	status: text('status').notNull(),
	reviewedBy: text('reviewed_by'),
	reviewedAt: text('reviewed_at'),
	rejectionReason: text('rejection_reason'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const importerStaffAudit = sqliteTable("importer_staff_audit", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	actorId: text('actor_id'),
	action: text('action').notNull(),
	targetType: text('target_type').notNull(),
	targetId: text('target_id').notNull(),
	oldState: text('old_state'),
	newState: text('new_state'),
	reason: text('reason'),
	metadata: text('metadata').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanTransferRequests = sqliteTable("scan_transfer_requests", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	fromUserId: text('from_user_id').notNull(),
	toUserId: text('to_user_id').notNull(),
	status: text('status').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	respondedAt: text('responded_at'),});

export const media = sqliteTable("media", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	provider: text('provider').notNull(),
	providerKey: text('provider_key').notNull(),
	mime: text('mime').notNull(),
	width: integer('width').notNull(),
	height: integer('height').notNull(),
	bytes: integer('bytes').notNull(),
	sha256: text('sha256').notNull(),
	createdBy: text('created_by').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	storageReady: integer('storage_ready', { mode: 'boolean' }).notNull(),
	purpose: text('purpose').notNull(),
	storagePoolId: text('storage_pool_id'),
	storageShardId: text('storage_shard_id'),
	botReference: text('bot_reference'),
	accessClass: text('access_class'),
	status: text('status'),
	pendingDeleteAt: text('pending_delete_at'),
	scanId: text('scan_id'),
	chapterId: text('chapter_id'),});

export const pages = sqliteTable("pages", {chapterId: text('chapter_id').notNull(),
	position: integer('position').notNull(),
	mediaId: text('media_id').notNull(),
	width: integer('width').notNull(),
	height: integer('height').notNull(),});

export const readingSessions = sqliteTable("reading_sessions", {userId: text('user_id').notNull(),
	chapterId: text('chapter_id').notNull(),
	nextPage: integer('next_page').notNull(),
	acceptedAt: text('accepted_at').notNull(),});

export const comments = sqliteTable("comments", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	userId: text('user_id').notNull(),
	workId: text('work_id').notNull(),
	chapterId: text('chapter_id'),
	parentId: text('parent_id'),
	body: text('body').notNull(),
	removed: integer('removed', { mode: 'boolean' }).notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const likes = sqliteTable("likes", {userId: text('user_id').notNull(),
	workId: text('work_id').notNull(),});

export const tags = sqliteTable("tags", {
	id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	name: text('name').notNull(),
	slug: text('slug').notNull(),
	kind: text('kind').notNull(),
});

export const workTags = sqliteTable("work_tags", {workId: text('work_id').notNull(),
	tagId: text('tag_id').notNull(),
	systemGenerated: integer('system_generated', { mode: 'boolean' }).notNull(),});

export const commentLikes = sqliteTable("comment_likes", {userId: text('user_id').notNull(),
	commentId: text('comment_id').notNull(),});

export const accessRoles = sqliteTable("access_roles", {userId: text('user_id').notNull(),
	role: text('role').notNull(),
	suspended: integer('suspended', { mode: 'boolean' }).notNull(),});

export const library = sqliteTable("library", {userId: text('user_id').notNull(),
	workId: text('work_id').notNull(),
	status: text('status').notNull(),
	favorite: integer('favorite', { mode: 'boolean' }).notNull(),
	following: integer('following', { mode: 'boolean' }).notNull(),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const reading = sqliteTable("reading", {userId: text('user_id').notNull(),
	chapterId: text('chapter_id').notNull(),
	page: integer('page').notNull(),
	maxPage: integer('max_page').notNull(),
	completedAt: text('completed_at'),
	startedAt: text('started_at').notNull(),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const auditLog = sqliteTable("audit_log", {id: integer('id').primaryKey().notNull(),
	actorId: text('actor_id'),
	action: text('action').notNull(),
	targetId: text('target_id'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	metadata: text('metadata').notNull(),});

export const settings = sqliteTable("settings", {
	key: text('key').notNull(),
	value: text('value').notNull(),
});

export const editorInvites = sqliteTable("editor_invites", {email: text('email').notNull(),
	createdBy: text('created_by').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const importerChapterMappings = sqliteTable("importer_chapter_mappings", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	source: text('source').notNull(),
	sourceChapterId: text('source_chapter_id').notNull(),
	chapterId: text('chapter_id'),
	workMappingId: text('work_mapping_id').notNull(),
	chapterNumber: real('chapter_number').notNull(),
	pageCount: integer('page_count').notNull(),
	status: text('status').notNull(),
	lastError: text('last_error'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),
	isPageProvider: integer('is_page_provider', { mode: 'boolean' }).notNull(),
	workId: text('work_id'),
	chapterSortKey: real('chapter_sort_key'),
	isGap: integer('is_gap', { mode: 'boolean' }).notNull(),});

export const workScans = sqliteTable("work_scans", {workId: text('work_id').notNull(),
	scanId: text('scan_id').notNull(),
	isPrimary: integer('is_primary', { mode: 'boolean' }).notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	status: text('status').notNull(),});

export const chapterScans = sqliteTable("chapter_scans", {chapterId: text('chapter_id').notNull(),
	scanId: text('scan_id').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const chapters = sqliteTable("chapters", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	workId: text('work_id').notNull(),
	number: real('number').notNull(),
	title: text('title').notNull(),
	publishedAt: text('published_at'),
	sourceId: text('source_id'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	origin: text('origin').notNull(),
	viewsTotal: integer('views_total').notNull(),});

export const importerSources = sqliteTable("importer_sources", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	name: text('name').notNull(),
	baseUrl: text('base_url').notNull(),
	enabled: integer('enabled').notNull(),
	rateLimitPerSecond: real('rate_limit_per_second').notNull(),
	syncIntervalMinutes: integer('sync_interval_minutes').notNull(),
	lastSyncAt: text('last_sync_at'),
	config: text('config').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),
	status: text('status').notNull(),
	cooldownUntil: text('cooldown_until'),
	blockedReason: text('blocked_reason'),
	blockedDetails: text('blocked_details').notNull(),
	lastHealthCheckAt: text('last_health_check_at'),});

export const importerWorkMappings = sqliteTable("importer_work_mappings", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	source: text('source').notNull(),
	sourceWorkId: text('source_work_id').notNull(),
	workId: text('work_id'),
	sourceSlug: text('source_slug').notNull(),
	sourceTitle: text('source_title').notNull(),
	syncStatus: text('sync_status').notNull(),
	metadata: text('metadata').notNull(),
	lastSyncedAt: text('last_synced_at'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),
	confidenceScore: real('confidence_score'),
	isPrimary: integer('is_primary', { mode: 'boolean' }),
	matchMethod: text('match_method'),
	frozenBy: text('frozen_by'),
	frozenAt: text('frozen_at'),
	freezeReason: text('freeze_reason'),});

export const works = sqliteTable("works", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	slug: text('slug').notNull(),
	title: text('title').notNull(),
	aliases: text('aliases', { mode: 'json' }).$type<string[]>().notNull(),
	synopsis: text('synopsis').notNull(),
	description: text('description').notNull(),
	author: text('author').notNull(),
	artist: text('artist').notNull(),
	kind: text('kind').notNull(),
	status: text('status').notNull(),
	year: integer('year'),
	ageRating: integer('age_rating').notNull(),
	published: integer('published', { mode: 'boolean' }).notNull(),
	featured: integer('featured', { mode: 'boolean' }).notNull(),
	coverId: text('cover_id'),
	sourceId: text('source_id'),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	searchText: text('search_text').notNull(),
	metadataProvenance: text('metadata_provenance').notNull(),
	contentRating: text('content_rating').notNull(),
	viewsTotal: integer('views_total').notNull(),
	latestChapterPublishedAt: text('latest_chapter_published_at'),});

export const chapterViews = sqliteTable("chapter_views", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	chapterId: text('chapter_id').notNull(),
	workId: text('work_id').notNull(),
	userId: text('user_id'),
	anonymousHash: text('anonymous_hash'),
	origin: text('origin').notNull(),
	viewedAt: text('viewed_at').notNull(),});

export const importerQueue = sqliteTable("importer_queue", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	taskType: text('task_type').notNull(),
	source: text('source').notNull(),
	priority: integer('priority').notNull(),
	payload: text('payload').notNull(),
	dedupeKey: text('dedupe_key').notNull(),
	status: text('status').notNull(),
	attempts: integer('attempts').notNull(),
	maxAttempts: integer('max_attempts').notNull(),
	lockedBy: text('locked_by'),
	lockedAt: text('locked_at'),
	leaseExpiresAt: text('lease_expires_at'),
	nextRunAt: text('next_run_at').notNull(),
	lastError: text('last_error'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),
	chapterSortKey: real('chapter_sort_key'),
	lastRecoveredError: text('last_recovered_error'),
	recoveredAt: text('recovered_at'),
	lastErrorAt: text('last_error_at'),
	retryReason: text('retry_reason'),
	progressCurrent: integer('progress_current'),
	progressTotal: integer('progress_total'),
	progressStage: text('progress_stage'),
	cancelRequested: integer('cancel_requested', { mode: 'boolean' }).notNull(),
	cancelledBy: text('cancelled_by'),
	cancelledAt: text('cancelled_at'),
	cancelReason: text('cancel_reason'),
	pausedBy: text('paused_by'),
	pausedAt: text('paused_at'),
	pauseReason: text('pause_reason'),});

export const importerCheckpoints = sqliteTable("importer_checkpoints", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	source: text('source').notNull(),
	cursorValue: text('cursor_value'),
	lastCheckedAt: text('last_checked_at').notNull(),
	metadata: text('metadata').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const importerTelemetry = sqliteTable("importer_telemetry", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	workerId: text('worker_id').notNull(),
	rssMb: integer('rss_mb').notNull(),
	heapUsedMb: integer('heap_used_mb').notNull(),
	heapTotalMb: integer('heap_total_mb').notNull(),
	externalMb: integer('external_mb').notNull(),
	arrayBuffersMb: integer('array_buffers_mb').notNull(),
	eventLoopLagMs: integer('event_loop_lag_ms').notNull(),
	concurrency: integer('concurrency').notNull(),
	activeJobs: integer('active_jobs').notNull(),
	cycleAction: text('cycle_action').notNull(),
	cycleReason: text('cycle_reason'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const importerJobMetrics = sqliteTable("importer_job_metrics", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	workerId: text('worker_id').notNull(),
	source: text('source').notNull(),
	workId: text('work_id'),
	chapterId: text('chapter_id'),
	chapterNumber: real('chapter_number').notNull(),
	pageCount: integer('page_count').notNull(),
	totalBytes: integer('total_bytes').notNull(),
	durationMs: integer('duration_ms').notNull(),
	downloadMs: integer('download_ms').notNull(),
	uploadMs: integer('upload_ms').notNull(),
	dbMs: integer('db_ms').notNull(),
	status: text('status').notNull(),
	errorMessage: text('error_message'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const members = sqliteTable("members", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	username: text('username').notNull(),
	displayName: text('display_name').notNull(),
	bio: text('bio').notNull(),
	avatarId: text('avatar_id'),
	xp: integer('xp').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	isTest: integer('is_test', { mode: 'boolean' }).notNull(),
	ageStatus: text('age_status').notNull(),
	blurNsfw: integer('blur_nsfw', { mode: 'boolean' }).notNull(),
	equippedTitleId: text('equipped_title_id'),
	equippedBadgeId: text('equipped_badge_id'),
	manualTitle: integer('manual_title', { mode: 'boolean' }).notNull(),
	manualBadge: integer('manual_badge', { mode: 'boolean' }).notNull(),
	bannerId: text('banner_id'),
	bannerPosition: text('banner_position').notNull(),
	avatarFrameId: text('avatar_frame_id'),
	nameColor: text('name_color'),
	equippedMedalId: text('equipped_medal_id'),
	equippedCommentBannerId: text('equipped_comment_banner_id'),
	isOnboarded: integer('is_onboarded', { mode: 'boolean' }).notNull(),
	equippedBannerId: text('equipped_banner_id'),
	privacyShowAchievements: integer('privacy_show_achievements', { mode: 'boolean' }).notNull(),
	privacyShowCosmetics: integer('privacy_show_cosmetics', { mode: 'boolean' }).notNull(),
	featuredAchievementId: text('featured_achievement_id'),
	privacyShowFavorites: integer('privacy_show_favorites', { mode: 'boolean' }).notNull(),
	privacyShowReadingHistory: integer('privacy_show_reading_history', { mode: 'boolean' }).notNull(),
	avatarCrop: text('avatar_crop'),
	bannerCrop: text('banner_crop'),
	privacyShowScans: integer('privacy_show_scans', { mode: 'boolean' }).notNull(),
	privacyScanMode: text('privacy_scan_mode').notNull(),
	adminHideScanBadges: integer('admin_hide_scan_badges', { mode: 'boolean' }).notNull(),});

export const storageShardGroups = sqliteTable("storage_shard_groups", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	poolId: text('pool_id').notNull(),
	scopeType: text('scope_type').notNull(),
	scopeId: text('scope_id').notNull(),
	strategy: text('strategy').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const storageShardGroupMembers = sqliteTable("storage_shard_group_members", {groupId: text('group_id').notNull(),
	shardId: text('shard_id').notNull(),
	weight: integer('weight').notNull(),
	priority: integer('priority').notNull(),});

export const mediaRecords = sqliteTable("media_records", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	purpose: text('purpose').notNull(),
	storagePoolId: text('storage_pool_id'),
	storageShardId: text('storage_shard_id'),
	backend: text('backend').notNull(),
	botReference: text('bot_reference').notNull(),
	channelId: text('channel_id'),
	messageId: text('message_id'),
	fileId: text('file_id'),
	uniqueFileId: text('unique_file_id'),
	checksum: text('checksum'),
	size: integer('size').notNull(),
	mimeType: text('mime_type').notNull(),
	scanId: text('scan_id'),
	workId: text('work_id'),
	chapterId: text('chapter_id'),
	uploadedBy: text('uploaded_by'),
	accessClass: text('access_class').notNull(),
	status: text('status').notNull(),
	pendingDeleteAt: text('pending_delete_at'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const mediaLocations = sqliteTable("media_locations", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	mediaId: text('media_id').notNull(),
	storageShardId: text('storage_shard_id').notNull(),
	role: text('role').notNull(),
	botReference: text('bot_reference').notNull(),
	channelId: text('channel_id'),
	messageId: text('message_id'),
	fileId: text('file_id').notNull(),
	status: text('status').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanStorageUsage = sqliteTable("scan_storage_usage", {scanId: text('scan_id').notNull(),
	pages: integer('pages').notNull(),
	bytes: integer('bytes').notNull(),
	uploads: integer('uploads').notNull(),
	failures: integer('failures').notNull(),
	activeUploads: integer('active_uploads').notNull(),
	throughput: real('throughput').notNull(),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const controlPlaneBackups = sqliteTable("control_plane_backups", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	backupId: text('backup_id').notNull(),
	schemaVersion: text('schema_version').notNull(),
	recordCounts: text('record_counts').notNull(),
	checksum: text('checksum').notNull(),
	dataPayload: text('data_payload'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const storagePools = sqliteTable("storage_pools", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	key: text('key').notNull(),
	displayName: text('display_name').notNull(),
	purpose: text('purpose').notNull(),
	reserved: integer('reserved').notNull(),
	enabled: integer('enabled').notNull(),
	overflowAllowed: integer('overflow_allowed', { mode: 'boolean' }).notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const storageShards = sqliteTable("storage_shards", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	poolId: text('pool_id').notNull(),
	backend: text('backend').notNull(),
	botReference: text('bot_reference').notNull(),
	channelId: text('channel_id').notNull(),
	displayName: text('display_name').notNull(),
	enabled: integer('enabled').notNull(),
	reserved: integer('reserved').notNull(),
	ownerScanId: text('owner_scan_id'),
	writeStatus: text('write_status').notNull(),
	readStatus: text('read_status').notNull(),
	activeUploads: integer('active_uploads').notNull(),
	queueDepth: integer('queue_depth').notNull(),
	recentSuccesses: integer('recent_successes').notNull(),
	recentFailures: integer('recent_failures').notNull(),
	latencyMs: integer('latency_ms').notNull(),
	throughput: real('throughput').notNull(),
	errorRate: real('error_rate').notNull(),
	cooldownUntil: text('cooldown_until'),
	weight: integer('weight').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),
	assignedChaptersCount: integer('assigned_chapters_count').notNull(),
	assignedPagesCount: integer('assigned_pages_count').notNull(),
	lastSelectedAt: text('last_selected_at'),
	recentBytes: integer('recent_bytes'),
	recentWrites: integer('recent_writes'),
	recentChapters: integer('recent_chapters'),
	lastWriteAt: text('last_write_at'),
	lastSuccessAt: text('last_success_at'),
	lastFailureAt: text('last_failure_at'),});

export const scanApplications = sqliteTable("scan_applications", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	openingId: text('opening_id').notNull(),
	positionId: text('position_id').notNull(),
	userId: text('user_id').notNull(),
	experience: text('experience').notNull(),
	availability: text('availability').notNull(),
	presentation: text('presentation').notNull(),
	portfolioUrl: text('portfolio_url'),
	contactInfo: text('contact_info').notNull(),
	status: text('status').notNull(),
	internalNotes: text('internal_notes'),
	reviewedBy: text('reviewed_by'),
	reviewedAt: text('reviewed_at'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const scanActivity = sqliteTable("scan_activity", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	userId: text('user_id'),
	action: text('action').notNull(),
	details: text('details').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanPositions = sqliteTable("scan_positions", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	name: text('name').notNull(),
	description: text('description').notNull(),
	icon: text('icon'),
	displayOrder: integer('display_order').notNull(),
	isActive: integer('is_active', { mode: 'boolean' }).notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanMemberPositions = sqliteTable("scan_member_positions", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	userId: text('user_id').notNull(),
	positionId: text('position_id').notNull(),
	isPrimary: integer('is_primary', { mode: 'boolean' }).notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	isPublic: integer('is_public', { mode: 'boolean' }).notNull(),
	hiddenByAdmin: integer('hidden_by_admin', { mode: 'boolean' }).notNull(),});

export const scanRecruitmentOpenings = sqliteTable("scan_recruitment_openings", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	positionId: text('position_id').notNull(),
	title: text('title').notNull(),
	description: text('description').notNull(),
	requirements: text('requirements').notNull(),
	language: text('language').notNull(),
	experienceLevel: text('experience_level').notNull(),
	availability: text('availability').notNull(),
	slots: integer('slots'),
	notes: text('notes').notNull(),
	status: text('status').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const scanStaffNotes = sqliteTable("scan_staff_notes", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	userId: text('user_id').notNull(),
	parentId: text('parent_id'),
	body: text('body').notNull(),
	isPinned: integer('is_pinned', { mode: 'boolean' }).notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const scanComments = sqliteTable("scan_comments", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	userId: text('user_id').notNull(),
	parentId: text('parent_id'),
	body: text('body').notNull(),
	removed: integer('removed', { mode: 'boolean' }).notNull(),
	pinned: integer('pinned', { mode: 'boolean' }).notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const scanCommentLikes = sqliteTable("scan_comment_likes", {userId: text('user_id').notNull(),
	commentId: text('comment_id').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanCommentReports = sqliteTable("scan_comment_reports", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	commentId: text('comment_id').notNull(),
	userId: text('user_id').notNull(),
	reason: text('reason').notNull(),
	status: text('status').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scans = sqliteTable("scans", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	name: text('name').notNull(),
	slug: text('slug').notNull(),
	description: text('description').notNull(),
	logoId: text('logo_id'),
	bannerId: text('banner_id'),
	website: text('website').notNull(),
	discord: text('discord').notNull(),
	fluxer: text('fluxer').notNull(),
	isOfficial: integer('is_official', { mode: 'boolean' }).notNull(),
	status: text('status').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),
	displayPreposition: text('display_preposition').notNull(),
	pauseUploads: integer('pause_uploads', { mode: 'boolean' }).notNull(),
	pauseRecruitment: integer('pause_recruitment', { mode: 'boolean' }).notNull(),
	emergencyMode: integer('emergency_mode', { mode: 'boolean' }).notNull(),
	emergencyReason: text('emergency_reason'),
	statusReason: text('status_reason'),
	bio: text('bio'),
	pinnedItems: text('pinned_items').notNull(),});

export const scanMembers = sqliteTable("scan_members", {scanId: text('scan_id').notNull(),
	userId: text('user_id').notNull(),
	role: text('role').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	isPublic: integer('is_public', { mode: 'boolean' }).notNull(),
	hiddenByAdmin: integer('hidden_by_admin', { mode: 'boolean' }).notNull(),
	availabilityStatus: text('availability_status').notNull(),
	availabilityMessage: text('availability_message'),
	availabilityUpdatedAt: text('availability_updated_at').notNull(),});

export const scanSlugHistory = sqliteTable("scan_slug_history", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	oldSlug: text('old_slug').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanGlobalAuditLog = sqliteTable("scan_global_audit_log", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id'),
	scanName: text('scan_name'),
	adminId: text('admin_id'),
	action: text('action').notNull(),
	reason: text('reason'),
	metadata: text('metadata'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanWorkUploaders = sqliteTable("scan_work_uploaders", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	workId: text('work_id').notNull(),
	userId: text('user_id').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanWorkflowStages = sqliteTable("scan_workflow_stages", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	name: text('name').notNull(),
	slug: text('slug').notNull(),
	description: text('description'),
	color: text('color'),
	displayOrder: integer('display_order').notNull(),
	isActive: integer('is_active', { mode: 'boolean' }).notNull(),
	required: integer('required', { mode: 'boolean' }).notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	dependencies: text('dependencies').notNull(),
	positionId: text('position_id'),
	allowedPositionIds: text('allowed_position_ids'),
	requiresOutput: integer('requires_output', { mode: 'boolean' }).notNull(),
	outputType: text('output_type').notNull(),
	dependencyOperator: text('dependency_operator').notNull(),});

export const scanTasks = sqliteTable("scan_tasks", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	workId: text('work_id'),
	chapterId: text('chapter_id'),
	stageId: text('stage_id'),
	title: text('title').notNull(),
	description: text('description'),
	assignedTo: text('assigned_to'),
	createdBy: text('created_by').notNull(),
	priority: text('priority').notNull(),
	status: text('status').notNull(),
	dueAt: text('due_at'),
	completedAt: text('completed_at'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const scanTaskComments = sqliteTable("scan_task_comments", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	taskId: text('task_id').notNull(),
	userId: text('user_id').notNull(),
	content: text('content').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanTaskHandoffs = sqliteTable("scan_task_handoffs", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	taskId: text('task_id').notNull(),
	fromUserId: text('from_user_id'),
	toUserId: text('to_user_id').notNull(),
	transferredBy: text('transferred_by').notNull(),
	reason: text('reason'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanRecruitmentQuestions = sqliteTable("scan_recruitment_questions", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	openingId: text('opening_id').notNull(),
	question: text('question').notNull(),
	questionType: text('question_type').notNull(),
	options: text('options'),
	required: integer('required', { mode: 'boolean' }).notNull(),
	displayOrder: integer('display_order').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanApplicationAnswers = sqliteTable("scan_application_answers", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	applicationId: text('application_id').notNull(),
	questionId: text('question_id').notNull(),
	answer: text('answer').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanIntegrations = sqliteTable("scan_integrations", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	platform: text('platform').notNull(),
	webhookUrl: text('webhook_url').notNull(),
	name: text('name').notNull(),
	isActive: integer('is_active', { mode: 'boolean' }).notNull(),
	notifyEvents: text('notify_events').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const scanWikiPages = sqliteTable("scan_wiki_pages", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	title: text('title').notNull(),
	slug: text('slug').notNull(),
	content: text('content').notNull(),
	category: text('category').notNull(),
	isPinned: integer('is_pinned', { mode: 'boolean' }).notNull(),
	createdBy: text('created_by'),
	updatedBy: text('updated_by'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const workGlossaryEntries = sqliteTable("work_glossary_entries", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	workId: text('work_id').notNull(),
	sourceTerm: text('source_term').notNull(),
	preferredTranslation: text('preferred_translation').notNull(),
	category: text('category').notNull(),
	notes: text('notes'),
	createdBy: text('created_by'),
	updatedBy: text('updated_by'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const workReferences = sqliteTable("work_references", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	workId: text('work_id').notNull(),
	title: text('title').notNull(),
	refType: text('ref_type').notNull(),
	content: text('content').notNull(),
	createdBy: text('created_by'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanChecklistConfigs = sqliteTable("scan_checklist_configs", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	name: text('name').notNull(),
	code: text('code').notNull(),
	required: integer('required', { mode: 'boolean' }).notNull(),
	displayOrder: integer('display_order').notNull(),});

export const scanOnboardingTemplates = sqliteTable("scan_onboarding_templates", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	title: text('title').notNull(),
	positionId: text('position_id'),
	items: text('items').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanMemberOnboarding = sqliteTable("scan_member_onboarding", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	userId: text('user_id').notNull(),
	completedItems: text('completed_items').notNull(),
	status: text('status').notNull(),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const scanPipelineTemplates = sqliteTable("scan_pipeline_templates", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	name: text('name').notNull(),
	code: text('code').notNull(),
	description: text('description'),
	stages: text('stages').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanChapterQcIssues = sqliteTable("scan_chapter_qc_issues", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	productionChapterId: text('production_chapter_id'),
	chapterId: text('chapter_id'),
	pageNumber: integer('page_number').notNull(),
	issueType: text('issue_type').notNull(),
	description: text('description').notNull(),
	assignedTo: text('assigned_to'),
	status: text('status').notNull(),
	resolvedBy: text('resolved_by'),
	resolvedAt: text('resolved_at'),
	createdBy: text('created_by').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const scanQcComments = sqliteTable("scan_qc_comments", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	issueId: text('issue_id').notNull(),
	userId: text('user_id').notNull(),
	content: text('content').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanChannels = sqliteTable("scan_channels", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	name: text('name').notNull(),
	slug: text('slug').notNull(),
	description: text('description'),
	category: text('category').notNull(),
	type: text('type').notNull(),
	displayOrder: integer('display_order').notNull(),
	isPrivate: integer('is_private', { mode: 'boolean' }).notNull(),
	allowedRoles: text('allowed_roles').notNull(),
	isArchived: integer('is_archived', { mode: 'boolean' }).notNull(),
	createdBy: text('created_by'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanMessages = sqliteTable("scan_messages", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	channelId: text('channel_id'),
	productionChapterId: text('production_chapter_id'),
	userId: text('user_id').notNull(),
	content: text('content').notNull(),
	mentions: text('mentions').notNull(),
	pinned: integer('pinned', { mode: 'boolean' }).notNull(),
	replyToId: text('reply_to_id'),
	threadCount: integer('thread_count').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),
	isEdited: integer('is_edited', { mode: 'boolean' }).notNull(),
	editedAt: text('edited_at'),
	deletedAt: text('deleted_at'),
	deletedBy: text('deleted_by'),});

export const scanMessageThreads = sqliteTable("scan_message_threads", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	parentMessageId: text('parent_message_id').notNull(),
	userId: text('user_id').notNull(),
	content: text('content').notNull(),
	isResolved: integer('is_resolved', { mode: 'boolean' }).notNull(),
	resolvedBy: text('resolved_by'),
	resolvedAt: text('resolved_at'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanMessageReactions = sqliteTable("scan_message_reactions", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	messageId: text('message_id').notNull(),
	userId: text('user_id').notNull(),
	emoji: text('emoji').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanChannelPreferences = sqliteTable("scan_channel_preferences", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	channelId: text('channel_id').notNull(),
	userId: text('user_id').notNull(),
	preference: text('preference').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanNotifications = sqliteTable("scan_notifications", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	userId: text('user_id').notNull(),
	type: text('type').notNull(),
	title: text('title').notNull(),
	body: text('body').notNull(),
	deepLink: text('deep_link'),
	isRead: integer('is_read', { mode: 'boolean' }).notNull(),
	readAt: text('read_at'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanNotificationPreferences = sqliteTable("scan_notification_preferences", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	userId: text('user_id').notNull(),
	directMentions: integer('direct_mentions').notNull(),
	roleMentions: integer('role_mentions').notNull(),
	tasks: integer('tasks').notNull(),
	chaptersWaiting: integer('chapters_waiting').notNull(),
	comments: integer('comments').notNull(),
	generalActivity: integer('general_activity').notNull(),
	emailEnabled: integer('email_enabled', { mode: 'boolean' }).notNull(),
	emailFrequency: text('email_frequency').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanEmailOutbox = sqliteTable("scan_email_outbox", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id'),
	recipientUserId: text('recipient_user_id').notNull(),
	recipientEmail: text('recipient_email').notNull(),
	subject: text('subject').notNull(),
	htmlBody: text('html_body').notNull(),
	status: text('status').notNull(),
	attempts: integer('attempts').notNull(),
	lastError: text('last_error'),
	idempotencyKey: text('idempotency_key'),
	scheduledAt: text('scheduled_at').notNull(),
	sentAt: text('sent_at'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	providerMessageId: text('provider_message_id'),
	deliveryStatus: text('delivery_status').notNull(),
	notificationId: text('notification_id'),
	priority: text('priority').notNull(),
	claimedAt: text('claimed_at'),
	claimedBy: text('claimed_by'),
	leaseExpiresAt: text('lease_expires_at'),
	cancellationReason: text('cancellation_reason'),
	cancelledBy: text('cancelled_by'),
	cancelledAt: text('cancelled_at'),
	sendStartedAt: text('send_started_at'),
	providerRequestKey: text('provider_request_key'),
	reconciledAt: text('reconciled_at'),
	reconciliationNotes: text('reconciliation_notes'),});

export const scanWikiVersions = sqliteTable("scan_wiki_versions", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	pageId: text('page_id').notNull(),
	scanId: text('scan_id').notNull(),
	title: text('title').notNull(),
	content: text('content').notNull(),
	versionNumber: integer('version_number').notNull(),
	authorId: text('author_id'),
	changeSummary: text('change_summary'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanTutorialVersions = sqliteTable("scan_tutorial_versions", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	tutorialId: text('tutorial_id').notNull(),
	scanId: text('scan_id').notNull(),
	versionNumber: integer('version_number').notNull(),
	title: text('title').notNull(),
	content: text('content').notNull(),
	updatedBy: text('updated_by'),
	changeSummary: text('change_summary'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanTutorialReads = sqliteTable("scan_tutorial_reads", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	tutorialId: text('tutorial_id').notNull(),
	userId: text('user_id').notNull(),
	scanId: text('scan_id').notNull(),
	isFavorite: integer('is_favorite', { mode: 'boolean' }).notNull(),
	readAt: text('read_at').notNull(),});

export const scanAcademyTutorials = sqliteTable("scan_academy_tutorials", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	title: text('title').notNull(),
	slug: text('slug').notNull(),
	category: text('category').notNull(),
	content: text('content').notNull(),
	isPublished: integer('is_published', { mode: 'boolean' }).notNull(),
	targetPositionId: text('target_position_id'),
	displayOrder: integer('display_order').notNull(),
	createdBy: text('created_by'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),
	status: text('status').notNull(),
	mandatoryForRoles: text('mandatory_for_roles'),});

export const scanProductionFiles = sqliteTable("scan_production_files", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	workId: text('work_id'),
	productionChapterId: text('production_chapter_id'),
	stageId: text('stage_id'),
	fileName: text('file_name').notNull(),
	byteSize: integer('byte_size').notNull(),
	mimeType: text('mime_type'),
	fileKey: text('file_key').notNull(),
	provider: text('provider').notNull(),
	version: integer('version').notNull(),
	uploadedBy: text('uploaded_by'),
	isCurrent: integer('is_current', { mode: 'boolean' }).notNull(),
	note: text('note'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	stageSlug: text('stage_slug'),
	inputFiles: text('input_files').notNull(),
	isStale: integer('is_stale', { mode: 'boolean' }).notNull(),
	staleReason: text('stale_reason'),
	storagePoolId: text('storage_pool_id'),
	storageShardId: text('storage_shard_id'),
	botReference: text('bot_reference'),
	telegramFileId: text('telegram_file_id'),
	sha256: text('sha256'),});

export const scanMuralPosts = sqliteTable("scan_mural_posts", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	authorId: text('author_id').notNull(),
	title: text('title').notNull(),
	content: text('content').notNull(),
	postType: text('post_type').notNull(),
	isPinned: integer('is_pinned', { mode: 'boolean' }).notNull(),
	pinnedAt: text('pinned_at'),
	pinnedBy: text('pinned_by'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const scanMuralComments = sqliteTable("scan_mural_comments", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	postId: text('post_id').notNull(),
	scanId: text('scan_id').notNull(),
	authorId: text('author_id').notNull(),
	parentCommentId: text('parent_comment_id'),
	content: text('content').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const scanMuralReactions = sqliteTable("scan_mural_reactions", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	postId: text('post_id'),
	commentId: text('comment_id'),
	scanId: text('scan_id').notNull(),
	userId: text('user_id').notNull(),
	emoji: text('emoji').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanAttachments = sqliteTable("scan_attachments", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	contextType: text('context_type').notNull(),
	contextId: text('context_id').notNull(),
	uploadedBy: text('uploaded_by').notNull(),
	originalFilename: text('original_filename').notNull(),
	safeFilename: text('safe_filename').notNull(),
	mimeType: text('mime_type').notNull(),
	size: integer('size').notNull(),
	checksum: text('checksum'),
	storageReference: text('storage_reference').notNull(),
	storageProvider: text('storage_provider').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanProductionChapters = sqliteTable("scan_production_chapters", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	workId: text('work_id').notNull(),
	chapterNumber: real('chapter_number').notNull(),
	chapterTitle: text('chapter_title'),
	targetChapterId: text('target_chapter_id'),
	status: text('status').notNull(),
	template: text('template').notNull(),
	checklistState: text('checklist_state').notNull(),
	currentStageSlug: text('current_stage_slug'),
	createdBy: text('created_by'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),
	chapterLabel: text('chapter_label'),
	chapterType: text('chapter_type').notNull(),
	chapterSortKey: real('chapter_sort_key').notNull(),
	priority: text('priority').notNull(),
	dueAt: text('due_at'),
	publicationVersion: integer('publication_version').notNull(),
	publishedSnapshot: text('published_snapshot').notNull(),
	pauseReason: text('pause_reason'),
	cancelReason: text('cancel_reason'),});

export const scanChapterStages = sqliteTable("scan_chapter_stages", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	chapterId: text('chapter_id'),
	stageId: text('stage_id').notNull(),
	status: text('status').notNull(),
	assignedTo: text('assigned_to'),
	dueAt: text('due_at'),
	notes: text('notes'),
	completedAt: text('completed_at'),
	completedBy: text('completed_by'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),
	productionChapterId: text('production_chapter_id'),
	claimedAt: text('claimed_at'),
	lastActivityAt: text('last_activity_at'),
	previousAssignedTo: text('previous_assigned_to'),
	rejectionReason: text('rejection_reason'),
	returnToStageId: text('return_to_stage_id'),
	isOverride: integer('is_override', { mode: 'boolean' }).notNull(),
	overrideReason: text('override_reason'),
	overrideBy: text('override_by'),
	overrideAction: text('override_action'),
	skipReason: text('skip_reason'),
	skippedBy: text('skipped_by'),
	notifiedAvailable: integer('notified_available', { mode: 'boolean' }).notNull(),
	availabilityVersion: integer('availability_version').notNull(),
	availabilityReason: text('availability_reason').notNull(),
	qcAssigneeId: text('qc_assignee_id'),});

export const scanWorkWorkflowOverrides = sqliteTable("scan_work_workflow_overrides", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	workId: text('work_id').notNull(),
	template: text('template').notNull(),
	customStages: text('custom_stages').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const scanChapterTimeline = sqliteTable("scan_chapter_timeline", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	productionChapterId: text('production_chapter_id').notNull(),
	stageId: text('stage_id'),
	stageSlug: text('stage_slug'),
	eventType: text('event_type').notNull(),
	userId: text('user_id'),
	userName: text('user_name'),
	details: text('details').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const chapterCreditSnapshots = sqliteTable("chapter_credit_snapshots", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	chapterId: text('chapter_id'),
	productionChapterId: text('production_chapter_id'),
	publicationVersion: integer('publication_version').notNull(),
	scanId: text('scan_id'),
	scanNameSnapshot: text('scan_name_snapshot').notNull(),
	scanSlugSnapshot: text('scan_slug_snapshot').notNull(),
	stageName: text('stage_name').notNull(),
	stageSlug: text('stage_slug').notNull(),
	positionName: text('position_name'),
	userId: text('user_id'),
	displayNameSnapshot: text('display_name_snapshot').notNull(),
	avatarIdSnapshot: text('avatar_id_snapshot'),
	roleOrder: integer('role_order').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanChannelReadStates = sqliteTable("scan_channel_read_states", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	scanId: text('scan_id').notNull(),
	channelId: text('channel_id').notNull(),
	userId: text('user_id').notNull(),
	lastReadMessageId: text('last_read_message_id'),
	lastReadAt: text('last_read_at').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const scanPipelineStageSeen = sqliteTable("scan_pipeline_stage_seen", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	userId: text('user_id').notNull(),
	scanId: text('scan_id').notNull(),
	chapterStageId: text('chapter_stage_id').notNull(),
	productionChapterId: text('production_chapter_id').notNull(),
	stageSlug: text('stage_slug').notNull(),
	availabilityVersion: integer('availability_version').notNull(),
	seenAt: text('seen_at').notNull(),});

export const notifications = sqliteTable("notifications", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	userId: text('user_id').notNull(),
	kind: text('kind').notNull(),
	body: text('body').notNull(),
	href: text('href').notNull(),
	dedupeKey: text('dedupe_key').notNull(),
	readAt: text('read_at'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	actorUserId: text('actor_user_id'),
	title: text('title'),
	type: text('type').notNull(),
	entityType: text('entity_type'),
	entityId: text('entity_id'),
	priority: text('priority').notNull(),
	scanId: text('scan_id'),
	context: text('context'),});

export const scanMessageMentions = sqliteTable("scan_message_mentions", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	messageId: text('message_id').notNull(),
	mentionType: text('mention_type').notNull(),
	targetUserId: text('target_user_id'),
	targetRoleId: text('target_role_id'),
	mentionText: text('mention_text').notNull(),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),});

export const uploadSessions = sqliteTable("upload_sessions", {id: text('id').primaryKey().notNull().$defaultFn(() => crypto.randomUUID()),
	userId: text('user_id').notNull(),
	scanId: text('scan_id'),
	workId: text('work_id').notNull(),
	chapterId: text('chapter_id'),
	poolKey: text('pool_key').notNull(),
	status: text('status').notNull(),
	totalPages: integer('total_pages').notNull(),
	uploadedPages: integer('uploaded_pages').notNull(),
	failedPages: integer('failed_pages').notNull(),
	pagesMetadata: text('pages_metadata').notNull(),
	errorMessage: text('error_message'),
	pausedAt: text('paused_at'),
	completedAt: text('completed_at'),
	createdAt: text('created_at').notNull().$defaultFn(() => new Date().toISOString()),
	updatedAt: text('updated_at').notNull().$defaultFn(() => new Date().toISOString()).$onUpdateFn(() => new Date().toISOString()),});

export const authUsers = sqliteTable("auth_users", {id: text('id').primaryKey(),
	email: text('email'),
	encryptedPassword: text('encrypted_password'),
	createdAt: text('created_at'),});


// Better Auth Tables
export const user = sqliteTable("user", {
	id: text('id').primaryKey(),
	name: text('name').notNull(),
	email: text('email').notNull().unique(),
	emailVerified: integer('emailVerified', { mode: 'boolean' }).notNull(),
	image: text('image'),
	createdAt: integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
	updatedAt: integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()).$onUpdateFn(() => new Date())
});

export const session = sqliteTable("session", {
	id: text('id').primaryKey(),
	expiresAt: integer('expiresAt', { mode: 'timestamp' }).notNull(),
	token: text('token').notNull().unique(),
	createdAt: integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
	updatedAt: integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()).$onUpdateFn(() => new Date()),
	ipAddress: text('ipAddress'),
	userAgent: text('userAgent'),
	userId: text('userId').notNull().references(() => user.id)
});

export const account = sqliteTable("account", {
	id: text('id').primaryKey(),
	accountId: text('accountId').notNull(),
	providerId: text('providerId').notNull(),
	userId: text('userId').notNull().references(() => user.id),
	accessToken: text('accessToken'),
	refreshToken: text('refreshToken'),
	idToken: text('idToken'),
	accessTokenExpiresAt: integer('accessTokenExpiresAt', { mode: 'timestamp' }),
	refreshTokenExpiresAt: integer('refreshTokenExpiresAt', { mode: 'timestamp' }),
	scope: text('scope'),
	password: text('password'),
	createdAt: integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
	updatedAt: integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()).$onUpdateFn(() => new Date())
});

export const verification = sqliteTable("verification", {
	id: text('id').primaryKey(),
	identifier: text('identifier').notNull(),
	value: text('value').notNull(),
	expiresAt: integer('expiresAt', { mode: 'timestamp' }).notNull(),
	createdAt: integer('createdAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
	updatedAt: integer('updatedAt', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()).$onUpdateFn(() => new Date())
});
